# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2955d8c962882b288bf4d92633ee9f3c726bb5f3901329968b6b30a645246cac4947274cacaecfc9f79ad3501677cd961deb4dac193f95ef8a092bf94901e0b8

test:
  secret_key_base: 2d2c543126d18d3ff4cb5fafe87a8c8356d78be1ea3df7ec9e87b7d91a5b494c809cbbffa46b951a3dae7c54ae508ca5cc33d5d2850a533fcbc6f8e91152a6b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
